//! Minimal PDF report generator.
//!
//! Produces a small, valid single-page PDF (text report) with no external
//! dependencies, so the shipped binary stays offline. This is the M1 "PDF design
//! report" deliverable; a richer layout (figures, tables) can layer on top later.

use engine_core::EngineDesign;

/// Render a simple text PDF design report from a design + its L0 result.
pub fn generate_report_pdf(design: &EngineDesign, l0: &sizing_l0::L0Result) -> Vec<u8> {
    let lines = build_text(design, l0);
    let content = content_stream(&lines);
    assemble_pdf(&content)
}

fn build_text(design: &EngineDesign, l0: &sizing_l0::L0Result) -> Vec<String> {
    vec![
        format!("Propulsor - Liquid Engine Design Report"),
        format!("Engine: {}", design.meta.name),
        format!("Propellant: {}", design.propellant.pair.label()),
        String::new(),
        format!("Operating Point"),
        format!("  Thrust:          {:.1} N ({:.1} lbf)", design.operating_point.thrust.as_si(), design.operating_point.thrust.as_si() * 0.224809),
        format!("  Chamber Pc:      {:.0} kPa ({:.0} psi)", design.operating_point.chamber_pressure.as_si() / 1000.0, design.operating_point.chamber_pressure.as_psi()),
        format!("  Mixture ratio:   {:.2}", design.operating_point.mixture_ratio.as_f64()),
        String::new(),
        format!("L0 Analytical Result"),
        format!("  Total flow:      {:.4} kg/s ({:.4} lb/s)", l0.total_flow.as_si(), l0.total_flow.as_lb_per_s()),
        format!("  Throat area:     {:.6} m2 ({:.4} in2)", l0.throat_area.as_si(), l0.throat_area.as_sq_inches()),
        format!("  Throat dia.:     {:.4} m ({:.3} in)", l0.throat_diameter.as_si(), l0.throat_diameter.as_inches()),
        format!("  Exit dia.:       {:.4} m ({:.3} in)", l0.exit_diameter.as_si(), l0.exit_diameter.as_inches()),
        format!("  Area ratio:      {:.2}", l0.area_ratio.as_f64()),
        format!("  Isp:             {:.0} s", l0.isp_s),
        format!("  c*:              {:.0} m/s", l0.c_star_m_s),
        format!("  T_c:             {:.0} K", l0.tc_k),
        format!("  Wall thickness:  {:.5} m ({:.4} in)", l0.wall_thickness.as_si(), l0.wall_thickness.as_inches()),
        format!("  Cooling gap:     {:.5} m ({:.4} in)", l0.cooling_gap.as_si(), l0.cooling_gap.as_inches()),
        String::new(),
        format!("Generated by Propulsor (APRO Works). Fidelity: L0 analytical."),
    ]
}

fn content_stream(lines: &[String]) -> Vec<u8> {
    let mut s = String::from("BT\n/F1 11 Tf\n");
    // Start near the top; move down one line per entry.
    let mut y = 760.0;
    for line in lines {
        s.push_str(&format!("1 0 0 1 50 {y:.0} Tm\n({}) Tj\n", escape(line)));
        y -= 16.0;
    }
    s.push_str("ET\n");
    s.into_bytes()
}

fn escape(s: &str) -> String {
    s.replace('\\', "\\\\").replace('(', "\\(").replace(')', "\\)")
}

/// Assemble a minimal PDF with a correct xref table.
fn assemble_pdf(content: &[u8]) -> Vec<u8> {
    let mut objects: Vec<Vec<u8>> = Vec::new();
    objects.push(b"<< /Type /Catalog /Pages 2 0 R >>".to_vec());
    objects.push(b"<< /Type /Pages /Kids [3 0 R] /Count 1 >>".to_vec());
    objects.push(
        b"<< /Type /Page /Parent 2 0 R /MediaBox [0 0 612 792] /Contents 4 0 R /Resources << /Font << /F1 5 0 R >> >> >>"
            .to_vec(),
    );
    let content_obj = format!("<< /Length {} >>\nstream\n", content.len())
        .into_bytes()
        .into_iter()
        .chain(content.iter().copied())
        .chain(b"\nendstream".iter().copied())
        .collect::<Vec<u8>>();
    objects.push(content_obj);
    objects.push(b"<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica >>".to_vec());

    let mut out: Vec<u8> = b"%PDF-1.4\n".to_vec();
    let mut offsets: Vec<usize> = Vec::new();
    for (i, obj) in objects.iter().enumerate() {
        offsets.push(out.len());
        out.extend_from_slice(format!("{} 0 obj\n", i + 1).as_bytes());
        out.extend_from_slice(obj);
        out.extend_from_slice(b"\nendobj\n");
    }

    let xref_pos = out.len();
    out.extend_from_slice(format!("xref\n0 {}\n", objects.len() + 1).as_bytes());
    out.extend_from_slice(b"0000000000 65535 f \n");
    for off in &offsets {
        out.extend_from_slice(format!("{:010} 00000 n \n", off).as_bytes());
    }
    out.extend_from_slice(format!("trailer\n<< /Size {} /Root 1 0 R >>\nstartxref\n{}\n%%EOF\n", objects.len() + 1, xref_pos).as_bytes());
    out
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn produces_valid_pdf_header() {
        let d = sizing_l0::krzycki_golden_design();
        let r0 = sizing_l0::solve_l0(&d, sizing_l0::L0Assumptions::default()).unwrap();
        let pdf = generate_report_pdf(&d, &r0);
        assert!(pdf.starts_with(b"%PDF-1.4"));
        assert!(pdf.ends_with(b"%%EOF\n"));
        assert!(pdf.len() > 200);
    }

    #[test]
    fn contour_csv_has_header_and_rows() {
        let pts = gasdynamics::contour::bell_contour(0.1, 0.4, 15.0, 20);
        let csv = crate::contour_csv(&pts);
        assert!(csv.starts_with("x_m,r_m\n"));
        assert_eq!(csv.lines().count(), 21);
    }
}
